[2025-08-16 22:24:32,685] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.create_dim_fecha manual__2025-08-16T22:24:29.163570+00:00 [queued]>
[2025-08-16 22:24:32,704] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_load_initial_data.create_dim_fecha manual__2025-08-16T22:24:29.163570+00:00 [queued]>
[2025-08-16 22:24:32,705] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 22:24:32,706] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2025-08-16 22:24:32,707] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-08-16 22:24:32,718] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_dim_fecha> on 2025-08-16 22:24:29.163570+00:00
[2025-08-16 22:24:32,725] {standard_task_runner.py:52} INFO - Started process 142 to run task
[2025-08-16 22:24:32,732] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '1_load_initial_data', 'create_dim_fecha', 'manual__2025-08-16T22:24:29.163570+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/initialise_data.py', '--cfg-path', '/tmp/tmpw0561_x1', '--error-file', '/tmp/tmp7i0f5zne']
[2025-08-16 22:24:32,735] {standard_task_runner.py:80} INFO - Job 17: Subtask create_dim_fecha
[2025-08-16 22:24:32,830] {task_command.py:369} INFO - Running <TaskInstance: 1_load_initial_data.create_dim_fecha manual__2025-08-16T22:24:29.163570+00:00 [running]> on host f4989c8fe60b
[2025-08-16 22:24:32,909] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=1_load_initial_data
AIRFLOW_CTX_TASK_ID=create_dim_fecha
AIRFLOW_CTX_EXECUTION_DATE=2025-08-16T22:24:29.163570+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-08-16T22:24:29.163570+00:00
[2025-08-16 22:24:32,914] {sql.py:262} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS dbt_raw_data.dim_fecha (
        fecha_id SERIAL PRIMARY KEY,
        fecha DATE NOT NULL,
        anio SMALLINT NOT NULL,
        mes SMALLINT NOT NULL,
        dia SMALLINT NOT NULL,
        dia_semana SMALLINT NOT NULL,
        nombre_dia_semana VARCHAR(20) NOT NULL,
        nombre_mes VARCHAR(20) NOT NULL,
        trimestre SMALLINT NOT NULL,
        anio_semana SMALLINT NOT NULL,
        es_fin_semana BOOLEAN NOT NULL
    );
    
[2025-08-16 22:24:32,936] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 22:24:32,980] {logging_mixin.py:115} WARNING - /usr/local/lib/python3.8/site-packages/airflow/models/connection.py:339 DeprecationWarning: The "schema" arg has been renamed to "database" as it contained the database name.Please use "database" to set the database name.
[2025-08-16 22:24:32,991] {base.py:68} INFO - Using connection ID 'dbt_postgres_instance_raw_data' for task execution.
[2025-08-16 22:24:33,007] {sql.py:375} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS dbt_raw_data.dim_fecha (
        fecha_id SERIAL PRIMARY KEY,
        fecha DATE NOT NULL,
        anio SMALLINT NOT NULL,
        mes SMALLINT NOT NULL,
        dia SMALLINT NOT NULL,
        dia_semana SMALLINT NOT NULL,
        nombre_dia_semana VARCHAR(20) NOT NULL,
        nombre_mes VARCHAR(20) NOT NULL,
        trimestre SMALLINT NOT NULL,
        anio_semana SMALLINT NOT NULL,
        es_fin_semana BOOLEAN NOT NULL
    );
    , parameters: None
[2025-08-16 22:24:33,044] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=1_load_initial_data, task_id=create_dim_fecha, execution_date=20250816T222429, start_date=20250816T222432, end_date=20250816T222433
[2025-08-16 22:24:33,105] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-08-16 22:24:33,145] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
